# Sentry Self-Hosted Docker Compose for CapRover
# This extends the base Sentry configuration with relay support

version: '3.8'

services:
  # Sentry Relay Service
  sentry-relay:
    image: getsentry/relay:latest
    container_name: sentry-relay
    restart: unless-stopped
    volumes:
      - ./relay-config.yml:/etc/relay/config.yml:ro
      - relay-data:/var/lib/relay
    ports:
      - "3000:3000"
    environment:
      - RELAY_LOG_LEVEL=debug
    networks:
      - sentry-network
    depends_on:
      - sentry-web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/relay/healthcheck/ready/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Sentry Web Service (existing)
  sentry-web:
    # Your existing Sentry web configuration
    environment:
      - SENTRY_RELAY_WHITELIST_PK=YOUR_RELAY_PUBLIC_KEY_HERE
      - SENTRY_USE_RELAY=true
    networks:
      - sentry-network

volumes:
  relay-data:
    driver: local

networks:
  sentry-network:
    driver: bridge